!!python/object:l3gs.L3GS_trainer.TrainerConfig
_target: !!python/name:l3gs.L3GS_trainer.Trainer ''
data: null
experiment_name: unnamed
gradient_accumulation_steps:
  camera_opt: 100
  color: 10
  shs: 10
load_checkpoint: null
load_config: null
load_dir: null
load_scheduler: true
load_step: null
log_gradients: false
logging: !!python/object:nerfstudio.configs.base_config.LoggingConfig
  local_writer: !!python/object:nerfstudio.configs.base_config.LocalWriterConfig
    _target: !!python/name:nerfstudio.utils.writer.LocalWriter ''
    enable: true
    max_log_size: 10
    stats_to_track: !!python/tuple
    - !!python/object/apply:nerfstudio.utils.writer.EventName
      - Train Iter (time)
    - !!python/object/apply:nerfstudio.utils.writer.EventName
      - Train Rays / Sec
    - !!python/object/apply:nerfstudio.utils.writer.EventName
      - Test PSNR
    - !!python/object/apply:nerfstudio.utils.writer.EventName
      - Vis Rays / Sec
    - !!python/object/apply:nerfstudio.utils.writer.EventName
      - Test Rays / Sec
    - !!python/object/apply:nerfstudio.utils.writer.EventName
      - ETA (time)
  max_buffer_size: 20
  profiler: basic
  relative_log_dir: !!python/object/apply:pathlib.PosixPath []
  steps_per_log: 10
machine: !!python/object:nerfstudio.configs.base_config.MachineConfig
  device_type: cuda
  dist_url: auto
  machine_rank: 0
  num_devices: 1
  num_machines: 1
  seed: 42
max_num_iterations: 30000
method_name: l3gs
mixed_precision: false
optimizers:
  camera_opt:
    optimizer: !!python/object:nerfstudio.engine.optimizers.AdamOptimizerConfig
      _target: &id001 !!python/name:torch.optim.adam.Adam ''
      eps: 1.0e-15
      lr: 0.001
      max_norm: null
      weight_decay: 0
    scheduler: !!python/object:nerfstudio.engine.schedulers.ExponentialDecaySchedulerConfig
      _target: &id002 !!python/name:nerfstudio.engine.schedulers.ExponentialDecayScheduler ''
      lr_final: 5.0e-05
      lr_pre_warmup: 1.0e-08
      max_steps: 30000
      ramp: cosine
      warmup_steps: 0
  color:
    optimizer: !!python/object:nerfstudio.engine.optimizers.AdamOptimizerConfig
      _target: *id001
      eps: 1.0e-15
      lr: 0.0005
      max_norm: null
      weight_decay: 0
    scheduler: !!python/object:nerfstudio.engine.schedulers.ExponentialDecaySchedulerConfig
      _target: *id002
      lr_final: 0.001
      lr_pre_warmup: 1.0e-08
      max_steps: 30000
      ramp: cosine
      warmup_steps: 0
  lerf:
    optimizer: !!python/object:nerfstudio.engine.optimizers.AdamOptimizerConfig
      _target: *id001
      eps: 1.0e-15
      lr: 0.0025
      max_norm: null
      weight_decay: 0
    scheduler: !!python/object:nerfstudio.engine.schedulers.ExponentialDecaySchedulerConfig
      _target: *id002
      lr_final: 0.001
      lr_pre_warmup: 1.0e-08
      max_steps: 15000
      ramp: cosine
      warmup_steps: 0
  opacity:
    optimizer: !!python/object:nerfstudio.engine.optimizers.AdamOptimizerConfig
      _target: *id001
      eps: 1.0e-15
      lr: 0.05
      max_norm: null
      weight_decay: 0
    scheduler: null
  rotation:
    optimizer: !!python/object:nerfstudio.engine.optimizers.AdamOptimizerConfig
      _target: *id001
      eps: 1.0e-15
      lr: 0.001
      max_norm: null
      weight_decay: 0
    scheduler: null
  scaling:
    optimizer: !!python/object:nerfstudio.engine.optimizers.AdamOptimizerConfig
      _target: *id001
      eps: 1.0e-15
      lr: 0.005
      max_norm: null
      weight_decay: 0
    scheduler: !!python/object:nerfstudio.engine.schedulers.ExponentialDecaySchedulerConfig
      _target: *id002
      lr_final: 0.001
      lr_pre_warmup: 1.0e-08
      max_steps: 30000
      ramp: cosine
      warmup_steps: 0
  xyz:
    optimizer: !!python/object:nerfstudio.engine.optimizers.AdamOptimizerConfig
      _target: *id001
      eps: 1.0e-15
      lr: 0.00016
      max_norm: null
      weight_decay: 0
    scheduler: !!python/object:nerfstudio.engine.schedulers.ExponentialDecaySchedulerConfig
      _target: *id002
      lr_final: 1.6e-06
      lr_pre_warmup: 1.0e-08
      max_steps: 30000
      ramp: cosine
      warmup_steps: 0
output_dir: !!python/object/apply:pathlib.PosixPath
- outputs
pipeline: !!python/object:l3gs.L3GS_pipeline.L3GSPipelineConfig
  _target: !!python/name:l3gs.L3GS_pipeline.L3GSPipeline ''
  datamanager: !!python/object:l3gs.data.L3GS_datamanager.L3GSDataManagerConfig
    _target: !!python/object/apply:_operator.getitem
    - !!python/name:l3gs.data.L3GS_datamanager.L3GSDataManager ''
    - !!python/name:l3gs.data.L3GS_dataset.L3GSDataset ''
    cache_images: cpu
    camera_res_scale_factor: 1.0
    clip_downscale_factor: 4
    data: null
    dataparser: !!python/object:l3gs.data.L3GS_dataparser.L3GSDataParserConfig
      _target: !!python/name:l3gs.data.L3GS_dataparser.L3GSDataParser ''
      aabb_scale: 1.0
      data: !!python/object/apply:pathlib.PosixPath []
      img_height: 480
      img_width: 848
      num_images: 1000
      scale_factor: 1.0
    eval_image_indices: !!python/tuple
    - 0
    eval_num_images_to_sample_from: -1
    eval_num_times_to_repeat_images: -1
    images_on_gpu: false
    masks_on_gpu: false
    network: !!python/object:l3gs.encoders.image_encoder.BaseImageEncoderConfig
      _target: !!python/name:l3gs.encoders.image_encoder.BaseImageEncoder ''
    patch_stride_scaler: 0.5
    patch_tile_size_range: !!python/tuple
    - 0.05
    - 0.5
    patch_tile_size_res: 7
  depthmodel: !!python/object:l3gs.monodepth.zoedepth_network.ZoeDepthNetworkConfig
    _target: !!python/name:l3gs.monodepth.zoedepth_network.ZoeDepthNetwork ''
    depth_model: ZoeD_N
    device: cuda:0
  model: !!python/object:l3gs.model.ll_gaussian_splatting.LLGaussianSplattingModelConfig
    _target: !!python/name:l3gs.model.ll_gaussian_splatting.LLGaussianSplattingModel ''
    camera_optimizer: !!python/object:nerfstudio.cameras.camera_optimizers.CameraOptimizerConfig
      _target: !!python/name:nerfstudio.cameras.camera_optimizers.CameraOptimizer ''
      mode: 'off'
      optimizer: null
      rot_l2_penalty: 0.001
      scheduler: null
      trans_l2_penalty: 0.01
    clip_loss_weight: 0.1
    collider_params:
      far_plane: 6.0
      near_plane: 2.0
    cull_alpha_thresh: 0.1
    cull_scale_thresh: 2.9
    cull_screen_size: 0.9
    densify_grad_thresh: 5.0e-05
    densify_size_thresh: 0.005
    enable_collider: true
    eval_num_rays_per_chunk: 4096
    loss_coefficients:
      rgb_loss_coarse: 1.0
      rgb_loss_fine: 1.0
    max_gauss_ratio: 5.0
    n_split_samples: 2
    num_downscales: 0
    prompt: null
    random_init: false
    refine_every: 75
    reset_alpha_every: 60
    resolution_schedule: 250
    sh_degree: 4
    sh_degree_interval: 1000
    split_screen_size: 0.005
    ssim_lambda: 0.2
    stop_screen_size_at: 4000
    stop_split_at: 30000
    warmup_length: 1000
  network: !!python/object:l3gs.encoders.openclip_encoder.OpenCLIPNetworkConfig
    _target: !!python/name:l3gs.encoders.openclip_encoder.OpenCLIPNetwork ''
    clip_model_pretrained: laion2b_s34b_b88k
    clip_model_type: ViT-B-16
    clip_n_dims: 512
    device: cuda:0
    negatives: !!python/tuple
    - object
    - things
    - stuff
    - texture
project_name: nerfstudio-project
prompt: null
relative_model_dir: !!python/object/apply:pathlib.PosixPath
- nerfstudio_models
save_only_latest_checkpoint: true
steps_per_eval_all_images: 100000
steps_per_eval_batch: 100
steps_per_eval_image: 100
steps_per_save: 2000
timestamp: 2024-01-30_003819
use_grad_scaler: false
viewer: !!python/object:nerfstudio.configs.base_config.ViewerConfig
  camera_frustum_scale: 0.1
  default_composite_depth: true
  image_format: jpeg
  jpeg_quality: 75
  make_share_url: false
  max_num_display_images: 512
  num_rays_per_chunk: 32768
  quit_on_train_completion: false
  relative_log_filename: viewer_log_filename.txt
  websocket_host: 0.0.0.0
  websocket_port: null
  websocket_port_default: 7007
vis: viewer_beta
